<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AdminPatrollers.aspx.cs" Inherits="AdminPatrollers" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
        <div id="content">

            <%=NavigatorSection %>
            <h3>Patrollers</h3>
                    <form id="form2" runat="server">
                        <table cellspacing="5" style="width: 210px">
                            <tr>
                                <td valign="top">
        
                     
            
            <asp:GridView ID="GridView1" runat="server" CellPadding="4"
                DataKeyNames="PatrollerID" DataSourceID="AccessDataSource1" ForeColor="#333333"
                GridLines="None" AllowSorting="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" Font-Size="8pt" Height="10px" />
                <EditRowStyle BackColor="#999999" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" Font-Size="8pt" Height="10px" />
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            </asp:GridView>
                                </td>
                                <td style="width: 428px; height: 27px" valign="top">
                                    <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateInsertButton="True" CellPadding="4" DataSourceID="AccessDataSource2"
                            ForeColor="#333333" GridLines="None" Height="1px" Width="90px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="PatrollerID">
                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" Font-Size="8pt" Height="10px" />
                            <EditRowStyle BackColor="#999999" Font-Size="8pt" Height="10px" />
                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" Font-Size="8pt" Height="10px" />
                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                            <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" Font-Size="8pt" Height="10px" />
                        </asp:DetailsView>
                                    &nbsp;</td>
                            </tr>
                        </table>
                        &nbsp;&nbsp;
                    <asp:AccessDataSource ID="AccessDataSource1" runat="server" DataFile="access_db/baldy.mdb"
                SelectCommand="SELECT [PatrollerID], [FirstName], [LastName], [Username], [Pass], [Email], [IsAdmin], [PType], [MinDays] FROM [Patroller] WHERE [SiteId]=?">
			<SelectParameters>
                                <asp:SessionParameter Type="Int32" Name="SiteID" SessionField="SiteID" />
			</SelectParameters>
            </asp:AccessDataSource>
                        <asp:AccessDataSource ID="AccessDataSource2" runat="server" DataFile="access_db/baldy.mdb"
                            SelectCommand="SELECT [PatrollerID], [FirstName], [LastName], [Username], [Pass], [Email], [IsAdmin], [PType], [MinDays] FROM [Patroller] WHERE ([PatrollerID] = ? AND [SiteID] = ?)"
                UpdateCommand="UPDATE [Patroller] SET [FirstName]=@FirstName, [LastName]=@LastName, 
                                                      [Username]=@UserName, [Pass]=@Pass, [Email]=@Email, [IsAdmin]=@IsAdmin, [PType]=@PType, [MinDays]=@MinDays 
                                                      WHERE [PatrollerID]=@PatrollerID"
                DeleteCommand="Delete from [Patroller] Where [PatrollerID]=@PatrollerID;" OnDeleted="AccessDataSource1_Deleted"
                InsertCommand="Insert into [Patroller] ([SiteID], [FirstName], [LastName], [Username], 
                                                        [Pass], [Email], [IsAdmin], [PType],
                                                        [MinDays]) 
                                                        values (@SiteID,
                                                        @FirstName, @LastName, @UserName,
                                                        @Pass, @Email, @IsAdmin, @PType, @MinDays )">        
                            <SelectParameters>
                                <asp:ControlParameter ControlID="GridView1" Name="PatrollerID" PropertyName="SelectedValue"
                                    Type="Int32" />                            
                                <asp:SessionParameter Type="Int32" Name="SiteID" SessionField="SiteID" />
                            </SelectParameters>
                            <InsertParameters> 
                                <asp:SessionParameter Type="Int32" Name="SiteID" SessionField="SiteID" />
                            </InsertParameters>
                        </asp:AccessDataSource>
                    </form>
            </div>
       
</asp:Content>

